// Curated health education videos.
// Thumbnails are pulled from YouTube's public CDN — no API key required.
// If a thumbnail fails to load, each card falls back to the emoji placeholder.
// To swap a video: update videoId + url. Search YouTube for the topic
// and copy the ?v= parameter from the URL.

export const EDUCATION_VIDEOS = [
  {
    id: 'v1',
    videoId: 'ayzN5f3qN8g',
    url:     'https://www.youtube.com/watch?v=ayzN5f3qN8g',
    title:   'How Does Your Period Work?',
    channel: 'TED-Ed',
    category:'Periods',
    color:   '#e75480',
    emoji:   '🩸',
  },
  {
    id: 'v2',
    videoId: 'Y3Cxnj-o1LM',
    url:     'https://www.youtube.com/watch?v=Y3Cxnj-o1LM',
    title:   'Menstrual Hygiene — Everything You Need to Know',
    channel: 'Health Education',
    category:'Hygiene',
    color:   '#7c3aed',
    emoji:   '🚿',
  },
  {
    id: 'v3',
    videoId: 'K7fE6BUQXJ4',
    url:     'https://www.youtube.com/watch?v=K7fE6BUQXJ4',
    title:   'Birth Control Pills — How They Work',
    channel: 'Planned Parenthood',
    category:'Contraception',
    color:   '#0891b2',
    emoji:   '💊',
  },
  {
    id: 'v4',
    videoId: 'xNjnL1qQqo8',
    url:     'https://www.youtube.com/watch?v=xNjnL1qQqo8',
    title:   'How to Use a Condom — Step by Step',
    channel: 'Planned Parenthood',
    category:'Contraception',
    color:   '#0891b2',
    emoji:   '🛡️',
  },
  {
    id: 'v5',
    videoId: 'C3CKxIevGOs',
    url:     'https://www.youtube.com/watch?v=C3CKxIevGOs',
    title:   'Emergency Contraception — The Morning-After Pill',
    channel: 'Planned Parenthood',
    category:'Contraception',
    color:   '#dc2626',
    emoji:   '⏱️',
  },
  {
    id: 'v6',
    videoId: 'sTmNXkRIklU',
    url:     'https://www.youtube.com/watch?v=sTmNXkRIklU',
    title:   'Understanding Ovulation & Fertility',
    channel: 'TED-Ed',
    category:'Fertility',
    color:   '#f59e0b',
    emoji:   '🥚',
  },
  {
    id: 'v7',
    videoId: 'gNsHbGKT7_Y',
    url:     'https://www.youtube.com/watch?v=gNsHbGKT7_Y',
    title:   'Female Sexual Health & Masturbation',
    channel: 'Sexual Health Education',
    category:'Sexual Health',
    color:   '#db2777',
    emoji:   '💗',
  },
  {
    id: 'v8',
    videoId: '8X7w79jFY7A',
    url:     'https://www.youtube.com/watch?v=8X7w79jFY7A',
    title:   'PMS vs. PMDD — What\'s the Difference?',
    channel: 'Medical Education',
    category:'Periods',
    color:   '#e75480',
    emoji:   '🌊',
  },
  {
    id: 'v9',
    videoId: 'oTOZ28E48PA',
    url:     'https://www.youtube.com/watch?v=oTOZ28E48PA',
    title:   'IUDs — The Long-Term Contraception Option',
    channel: 'Planned Parenthood',
    category:'Contraception',
    color:   '#0891b2',
    emoji:   '🔵',
  },
  {
    id: 'v10',
    videoId: 'RXWp-dYNIig',
    url:     'https://www.youtube.com/watch?v=RXWp-dYNIig',
    title:   'Period Pain — Why Cramps Happen & How to Manage',
    channel: 'Medical Education',
    category:'Periods',
    color:   '#e75480',
    emoji:   '😣',
  },
];

export const HEALTH_FACTS = [
  {
    id: 'f1', emoji: '🩸',
    title: 'Period blood is clean',
    body: 'Menstrual fluid is blood, uterine lining, and vaginal secretions — completely sterile and not "dirty".',
    color: '#e75480',
  },
  {
    id: 'f2', emoji: '🛡️',
    title: 'Only condoms prevent STIs',
    body: 'Hormonal birth control prevents pregnancy but does NOT protect against sexually transmitted infections. Use condoms too.',
    color: '#0891b2',
  },
  {
    id: 'f3', emoji: '💊',
    title: 'The pill is 99% effective',
    body: 'Combined oral contraceptives are over 99% effective with perfect use, and ~91% with typical use.',
    color: '#7c3aed',
  },
  {
    id: 'f4', emoji: '⏱️',
    title: 'Plan B works within 72 hrs',
    body: 'Emergency contraception is most effective within 72 hours but can work up to 5 days after unprotected sex.',
    color: '#dc2626',
  },
  {
    id: 'f5', emoji: '🌡️',
    title: 'Temperature rises at ovulation',
    body: 'Basal body temperature rises ~0.5°C after ovulation due to progesterone — a natural sign you can track.',
    color: '#f59e0b',
  },
  {
    id: 'f6', emoji: '🧘',
    title: 'Masturbation can ease cramps',
    body: 'Orgasms release endorphins and oxytocin that can relieve menstrual cramps and reduce stress naturally.',
    color: '#db2777',
  },
  {
    id: 'f7', emoji: '🫧',
    title: 'Discharge is totally normal',
    body: 'Vaginal discharge changes throughout your cycle. Clear, stretchy discharge around ovulation is a healthy sign.',
    color: '#059669',
  },
  {
    id: 'f8', emoji: '🌿',
    title: 'Change protection every 4–8 hrs',
    body: 'Pads and tampons should be changed every 4–8 hours. Menstrual cups can safely stay in for up to 12 hours.',
    color: '#16a34a',
  },
  {
    id: 'f9', emoji: '🔄',
    title: 'Cycles vary — 21–35 days is normal',
    body: 'There is no single "normal" cycle length. Stress, illness, and weight changes can all shift your cycle timing.',
    color: '#e75480',
  },
  {
    id: 'f10', emoji: '❤️',
    title: 'Sex during your period is safe',
    body: 'Period sex is physically safe and can relieve cramps. STI risk remains the same, so always use protection.',
    color: '#e75480',
  },
];
