// In-app educational articles, shown in a reader modal on Home.
// These replace an earlier version that linked out to YouTube videos —
// several of those video IDs no longer resolved to real videos, so the
// same topics are covered here as short, self-contained articles instead
// (no dependency on external video availability).
// To add a topic: append an entry with a few `sections`, each a short
// { heading, body } block.

export const EDUCATION_TOPICS = [
  {
    id: 't1',
    title:    'How Does Your Period Work?',
    category: 'Periods',
    color:    '#e75480',
    emoji:    '🩸',
    readTime: '3 min read',
    summary:  "A quick tour of what's happening in your body during your cycle.",
    sections: [
      { heading: 'The menstrual cycle, explained', body: "Your cycle is your body's roughly monthly process of preparing for a possible pregnancy. It's driven by four hormones — estrogen, progesterone, FSH, and LH — rising and falling in a repeating pattern, usually every 21–35 days." },
      { heading: 'Four phases', body: 'Menstrual phase: the uterine lining sheds if no pregnancy occurred — this is your period. Follicular phase: your body prepares an egg and rebuilds the lining. Ovulation: a mature egg is released. Luteal phase: the lining thickens again; if no pregnancy happens, hormones drop and the cycle restarts.' },
      { heading: "What you're actually bleeding", body: "Period blood is a mix of blood, uterine tissue, and cervical mucus — not \"dirty,\" just your body clearing out what it built and didn't need." },
    ],
  },
  {
    id: 't2',
    title:    'Menstrual Hygiene — Everything You Need to Know',
    category: 'Hygiene',
    color:    '#7c3aed',
    emoji:    '🚿',
    readTime: '3 min read',
    summary:  'Product basics, change frequency, and everyday care.',
    sections: [
      { heading: 'Choosing a product', body: "Pads, tampons, menstrual cups, and period underwear all work — pick what's comfortable, and feel free to mix products across your cycle or flow level." },
      { heading: 'How often to change', body: 'Pads and tampons: every 4–8 hours, even on light days. Never wear a tampon longer than 8 hours — that raises the risk of toxic shock syndrome (TSS). Menstrual cups can safely stay in for up to 12 hours.' },
      { heading: 'Everyday hygiene', body: "Wash your hands before and after changing products, and rinse the outer genital area with warm water — no soap or douching needed, since the vagina cleans itself. Change out of a wet swimsuit or damp underwear promptly." },
      { heading: 'When to see a doctor', body: 'Sudden fever, rash, or dizziness while using a tampon is a medical emergency (possible TSS) — remove it and seek care immediately.' },
    ],
  },
  {
    id: 't3',
    title:    'Birth Control Pills — How They Work',
    category: 'Contraception',
    color:    '#0891b2',
    emoji:    '💊',
    readTime: '3 min read',
    summary:  'The mechanism, the effectiveness, and what to know before starting.',
    sections: [
      { heading: 'How they work', body: 'Combined pills contain estrogen and progestin, which stop ovulation, thicken cervical mucus to block sperm, and thin the uterine lining. Progestin-only "mini pills" mainly work by thickening cervical mucus.' },
      { heading: 'Effectiveness', body: "Over 99% effective with perfect use, about 91% with typical use — most real-world failures come from missed or late pills rather than the pill itself not working." },
      { heading: 'Taking them', body: 'Combined pills are usually taken at the same time daily for 21 days, followed by placebo/break days. Mini pills need to be taken within the same 3-hour window every day to stay effective.' },
      { heading: 'Also worth knowing', body: "The pill doesn't protect against STIs, so pair it with condoms if that's a concern. It's prescription-only — a doctor can help you find the right formulation for you." },
    ],
  },
  {
    id: 't4',
    title:    'How to Use a Condom — Step by Step',
    category: 'Contraception',
    color:    '#0891b2',
    emoji:    '🛡️',
    readTime: '2 min read',
    summary:  'Doing it right matters — here\'s the full process.',
    sections: [
      { heading: 'Before you start', body: "Check the expiration date, and squeeze the package to confirm there's air inside — a sign it hasn't been damaged. Use a fresh condom every time, for every act of penetration." },
      { heading: 'Putting it on', body: 'Pinch the tip to remove air, then roll it down the entire erect penis before any genital contact. Only use water- or silicone-based lubricant — oil-based products like lotion or Vaseline can weaken latex.' },
      { heading: 'During and after', body: "Check occasionally that it hasn't slipped. After ejaculation, hold the base and withdraw while still erect, then remove and tie it off away from a partner's skin." },
      { heading: 'Why it matters', body: "Condoms are the only method that also protects against most STIs — pairing them with another method (like the pill) protects against both pregnancy and infection." },
    ],
  },
  {
    id: 't5',
    title:    'Emergency Contraception — The Morning-After Pill',
    category: 'Contraception',
    color:    '#dc2626',
    emoji:    '⏱️',
    readTime: '3 min read',
    summary:  'A backup option — what it is, and how soon you need to act.',
    sections: [
      { heading: 'What it is', body: 'Emergency contraception (EC), often called the "morning-after pill," is a backup method used after unprotected sex or contraception failure — not a regular birth control method.' },
      { heading: 'How it works', body: 'Most EC pills (levonorgestrel or ulipristal acetate) delay or prevent ovulation. They do not end an existing pregnancy and are not the same as the abortion pill.' },
      { heading: 'Timing matters', body: 'Levonorgestrel pills (like Plan B) work best within 72 hours but can help up to 5 days after. Ulipristal acetate (ella) stays effective for the full 5 days. A copper IUD inserted within 5 days is actually the most effective EC option.' },
      { heading: 'Good to know', body: "EC is available over the counter in many places without a prescription, and can be used more than once if needed — though it isn't meant to replace regular contraception." },
    ],
  },
  {
    id: 't6',
    title:    'Understanding Ovulation & Fertility',
    category: 'Fertility',
    color:    '#f59e0b',
    emoji:    '🥚',
    readTime: '3 min read',
    summary:  'What ovulation is, and how to recognize your fertile window.',
    sections: [
      { heading: 'What ovulation is', body: 'Around the middle of your cycle, a mature egg is released from an ovary and travels down the fallopian tube — this typically happens once per cycle.' },
      { heading: 'The fertile window', body: 'An egg survives about 12–24 hours after release, but sperm can live in the body up to 5 days — so the "fertile window" spans roughly 6 days: the 5 days before ovulation through the day itself.' },
      { heading: 'Signs your body gives', body: 'Cervical mucus becomes clear and stretchy (like egg whites), basal body temperature rises slightly after ovulation, and some people feel mild pelvic twinges (mittelschmerz).' },
      { heading: 'Why it matters', body: "Tracking these signs helps whether you're trying to conceive or avoid pregnancy — though for reliable contraception, pair tracking with another method." },
    ],
  },
  {
    id: 't7',
    title:    'Female Sexual Health & Masturbation',
    category: 'Sexual Health',
    color:    '#db2777',
    emoji:    '💗',
    readTime: '2 min read',
    summary:  "It's normal, common, and worth understanding without stigma.",
    sections: [
      { heading: "It's normal — and common", body: 'Masturbation is a safe, healthy, and common way to learn about your own body, relieve stress, and improve sleep. There is no physical downside to it.' },
      { heading: 'Possible benefits', body: 'Orgasms release endorphins and oxytocin, which can help ease menstrual cramps, reduce stress, and support better sleep.' },
      { heading: 'Hygiene basics', body: 'Wash your hands before and after, and clean any toys with warm water and mild, unscented soap (or per the manufacturer\'s instructions) between uses.' },
      { heading: 'Talking to a doctor', body: 'If sex or masturbation is ever painful, or you notice unusual discharge, odor, or itching, it\'s worth mentioning to a healthcare provider — these are common and very treatable.' },
    ],
  },
  {
    id: 't8',
    title:    "PMS vs. PMDD — What's the Difference?",
    category: 'Periods',
    color:    '#e75480',
    emoji:    '🌊',
    readTime: '3 min read',
    summary:  "It's less about symptoms, more about severity and impact.",
    sections: [
      { heading: 'PMS (Premenstrual Syndrome)', body: 'Up to 90% of menstruating people experience some PMS — physical and emotional symptoms like bloating, breast tenderness, irritability, or fatigue in the 1–2 weeks before a period, easing once bleeding starts.' },
      { heading: 'PMDD (Premenstrual Dysphoric Disorder)', body: 'A more severe, less common condition (about 3–8% of people) involving intense mood symptoms — significant depression, anxiety, irritability, or hopelessness — that noticeably disrupt daily life, relationships, or work.' },
      { heading: 'Key difference', body: "It's less about which symptoms you have and more about severity: PMDD symptoms are debilitating, not just uncomfortable, and specifically clear up within a few days of your period starting." },
      { heading: 'What helps', body: 'PMS often responds to lifestyle changes (exercise, sleep, reducing salt/caffeine). PMDD usually needs professional support — therapy, certain antidepressants, or hormonal treatment. If mood symptoms feel unmanageable, talk to a doctor.' },
    ],
  },
  {
    id: 't9',
    title:    'IUDs — The Long-Term Contraception Option',
    category: 'Contraception',
    color:    '#0891b2',
    emoji:    '🔵',
    readTime: '3 min read',
    summary:  'Hormonal vs. copper, effectiveness, and what to expect.',
    sections: [
      { heading: 'Two types', body: 'Hormonal IUDs release progestin to thicken cervical mucus and thin the uterine lining. The copper IUD is hormone-free and works by making the uterus inhospitable to sperm.' },
      { heading: 'How effective', body: "Both types are over 99% effective — among the most reliable reversible contraception available, since there's no daily action required." },
      { heading: 'How long they last', body: 'Hormonal IUDs last 3–8 years depending on the brand; the copper IUD lasts up to 10–12 years. Either can be removed early by a doctor at any time, with fertility returning quickly.' },
      { heading: 'What to expect', body: 'Insertion takes just a few minutes in-office and can cause brief cramping. Some spotting or irregular bleeding in the first few months is common and usually settles down.' },
    ],
  },
  {
    id: 't10',
    title:    'Period Pain — Why Cramps Happen & How to Manage',
    category: 'Periods',
    color:    '#e75480',
    emoji:    '😣',
    readTime: '3 min read',
    summary:  "The biology behind cramps, and what actually helps.",
    sections: [
      { heading: 'Why cramps happen', body: 'Your uterus produces prostaglandins, hormone-like chemicals that trigger it to contract and shed its lining. Higher prostaglandin levels generally mean stronger cramps.' },
      { heading: 'What helps', body: 'Heat (a heating pad or warm bath), light exercise or stretching, over-the-counter NSAIDs like ibuprofen (which directly reduce prostaglandin production), and staying hydrated can all ease symptoms.' },
      { heading: 'Other things that help some people', body: 'Orgasms, massage, and reducing caffeine or salt intake around your period.' },
      { heading: 'When to see a doctor', body: "Pain severe enough to disrupt daily life, that doesn't respond to over-the-counter medication, or that comes with heavy bleeding could point to conditions like endometriosis or fibroids — always worth getting checked rather than assuming severe pain is \"normal.\"" },
    ],
  },
];

export const HEALTH_FACTS = [
  {
    id: 'f1', emoji: '🩸',
    title: 'Period blood is clean',
    body: 'Menstrual fluid is blood, uterine lining, and vaginal secretions — completely sterile and not "dirty".',
    color: '#e75480',
  },
  {
    id: 'f2', emoji: '🛡️',
    title: 'Only condoms prevent STIs',
    body: 'Hormonal birth control prevents pregnancy but does NOT protect against sexually transmitted infections. Use condoms too.',
    color: '#0891b2',
  },
  {
    id: 'f3', emoji: '💊',
    title: 'The pill is 99% effective',
    body: 'Combined oral contraceptives are over 99% effective with perfect use, and ~91% with typical use.',
    color: '#7c3aed',
  },
  {
    id: 'f4', emoji: '⏱️',
    title: 'Plan B works within 72 hrs',
    body: 'Emergency contraception is most effective within 72 hours but can work up to 5 days after unprotected sex.',
    color: '#dc2626',
  },
  {
    id: 'f5', emoji: '🌡️',
    title: 'Temperature rises at ovulation',
    body: 'Basal body temperature rises ~0.5°C after ovulation due to progesterone — a natural sign you can track.',
    color: '#f59e0b',
  },
  {
    id: 'f6', emoji: '🧘',
    title: 'Masturbation can ease cramps',
    body: 'Orgasms release endorphins and oxytocin that can relieve menstrual cramps and reduce stress naturally.',
    color: '#db2777',
  },
  {
    id: 'f7', emoji: '🫧',
    title: 'Discharge is totally normal',
    body: 'Vaginal discharge changes throughout your cycle. Clear, stretchy discharge around ovulation is a healthy sign.',
    color: '#059669',
  },
  {
    id: 'f8', emoji: '🌿',
    title: 'Change protection every 4–8 hrs',
    body: 'Pads and tampons should be changed every 4–8 hours. Menstrual cups can safely stay in for up to 12 hours.',
    color: '#16a34a',
  },
  {
    id: 'f9', emoji: '🔄',
    title: 'Cycles vary — 21–35 days is normal',
    body: 'There is no single "normal" cycle length. Stress, illness, and weight changes can all shift your cycle timing.',
    color: '#e75480',
  },
  {
    id: 'f10', emoji: '❤️',
    title: 'Sex during your period is safe',
    body: 'Period sex is physically safe and can relieve cramps. STI risk remains the same, so always use protection.',
    color: '#e75480',
  },
];
